sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t andrew428park/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrew428park/docker-react npm run test
